### ISSUE TITLE
VTypes

### ISSUE THREAD

**Issue by shroffk** [epics-base/epicsCoreJava#15]
Add type definitions for 
- [x] Image (with support for both signed and unsigned values)
- [x] Table

**Comment by shroffk** [comment]
@kasemir @ralphlange @gcarcassi @georgweiss 
I have added preliminary implementations for the Image and Table in preparation for the 7.0.2 release
The Types can improved latter unless there are major flaws.

Bruno Martins had requested the addition of additional information about compression, however I am not sure if these should be included in the VImage or should be handled in the connection library mapping the NTNDArray to VImage

```
//f) Compression algorithm
    structure codec_t codec
        string name
        any    parameters
```

**Comment by kasemir** [comment]
I agree with your sentiment that the compression is handled when converting the NTNDArray into the VImage.

What I need in the VImage is the grayscale intensity or the color RGB value for the pixel at location (x, y). This is used to paint the image, and to determine cursor information. If the underlying  NTNDArray is compressed or not doesn't matter to me, I'd prefer to see the un-compressed data over knowing the compression detail and then having to uncompress it myself.

**Comment by shroffk** [comment]
The current implementation with the ListNumber will give you all the data point for tooltips, profiles, crosshairs, etc...
The VImageType and VImageDataType will tell if the image it RGB or Mono with unsigned Int's or singed doubles.

**Comment by kasemir** [comment]
Right. As before, plus now with unsigned, is good.
