### ISSUE TITLE
RPCClientImpl request method calls waitResponse() with timeout in milliseconds instead of seconds

### ISSUE THREAD

**Issue by BenBradnick** [epics-base/epicsCoreJava#34]
Relevant lines: https://github.com/epics-base/epicsCoreJava/blob/bdba05e743a983b1b4a3ea8201967dd5bc0dea8c/pvAccessJava/src/org/epics/pvaccess/client/rpc/RPCClientImpl.java#L117-L145

The timeLeft variable is already in milliseconds - which is then "converted" into milliseconds again in waitResponse: https://github.com/epics-base/epicsCoreJava/blob/bdba05e743a983b1b4a3ea8201967dd5bc0dea8c/pvAccessJava/src/org/epics/pvaccess/client/rpc/RPCClientImpl.java#L180-L196

This means that the actual timeout ends up being a factor of 1,000 times larger than desired.

**Comment by shroffk** [comment]
Thanks @BenBradnick you are right.
Since the public waitResponse methods javadoc describes the timeout as being in seconds I will update the timeLeft calculation so that it holds a time with units seconds.
