### ISSUE TITLE
Missing VStringArray and VEnumArray and VStatistics

### ISSUE THREAD

**Issue by kasemir** [epics-base/epicsCoreJava#41]
VTypes used to include VStringArray. CA as well as local PVs can create string arrays, but updated VType cannot wrap it?

**Comment by kasemir** [comment]
VType has related section commented-out, so the idea to support VStringArray used to be there:

https://github.com/epics-base/epicsCoreJava/blob/master/epics-vtype/vtype/src/main/java/org/epics/vtype/VType.java#L164

**Comment by kasemir** [comment]
VEnumArray is also missing

**Comment by shroffk** [comment]
@kasemir I don't have enum array...but should we merge this?

**Comment by kasemir** [comment]
Missing boolean array as well. Would that create an epics-core 7.0.3, and then I update the phoebus code to use it, removing the then obsolete implementations in phoebus core-vtype?

**Comment by kasemir** [comment]
I think you mentioned VStatistics had not been added because you're unclear about the display information. Indeed the VStatistics in phoebus core-vtype have no display, and they use plain double instead of Double objects. Use that?

**Comment by shroffk** [comment]
I will mostly have to prepare a new release 7.0.3
I will add the boolean array before that...any other show stoppers?
