### ISSUE TITLE
VTable has no public methods for getting data

### ISSUE THREAD

**Issue by kasemir** [epics-base/epicsCoreJava#42]
VTable, https://github.com/epics-base/epicsCoreJava/blob/master/epics-vtype/vtype/src/main/java/org/epics/vtype/VTable.java, is useless. All the `get*()` methods are package-private, so no way to get the data.

**Comment by shroffk** [comment]
The VTable was ported without the VTableFactory (o.d.vtype.table.)
Is the submodules .table the way to go or should we follow the api pattern of the rest of the types and include the table operations in the VTable itself

**Comment by kasemir** [comment]
The problem is not a VTableFactory.
You can create a table just fine with `VTable.of(..)`.
But then you can't see any of the data, because `VTable.getColumnCount()`, `getColumnData()` are all private, package level access only.

Need to be public.

**Comment by shroffk** [comment]
It is not just the factory...
The phoebus VTable also has all the get methods package private.
https://github.com/shroffk/phoebus/blob/master/core/vtype/src/main/java/org/phoebus/vtype/VTable.java

All the mechanisms for extracting data from the table have been kept package private with another package "table" consisting of classes implementing the VColumn etc.

For the VImage I had enough information to make public the data extraction methods...not so sure about the VTable usage.

I can update the VTable methods to have the same visibility as IVTable...

**Comment by shroffk** [comment]
Between this, and issue #41 I think I have enough to justify a new release of the epics-vtype.
We can resolve all of these in the 1.0.1 release

**Comment by kasemir** [comment]
Yes, making `VTable.get*` public would work.

Also, can the `ArrayXXXX.wrappedArray()` methods be public?
That saves some array copies, #43

**Comment by kasemir** [comment]
Added an introspection hack to read VTable.
It works, so the data is basically OK, just need public methods to read it.

**Comment by shroffk** [comment]
@kasemir can we close this

**Comment by kasemir** [comment]
We can close this issue because the EPICS code source code has been updated.
We still need to release it and/or update the phoebus dependencies to a 'snapshot' so we can benefit from the fox.
