### ISSUE TITLE
No longer possible to get wrapped array

### ISSUE THREAD

**Issue by kasemir** [epics-base/epicsCoreJava#43]
`CollectionNumbers.wrappedArray(list)` has been removed, and `ArrayNumber.wrappedArray()` is private, so there is no longer a way to get to the raw array.
This means when starting with a plain array, which for use with the VType must be wrapped as an Array*, you can no longer get back at the array, so now you need to copy it.

**Comment by shroffk** [comment]
Please refer to 
https://github.com/epics-base/epicsCoreJava/blob/master/epics-util/src/main/java/org/epics/util/array/UnsafeUnwrapper.javahttps://github.com/epics-base/epicsCoreJava/blob/master/epics-util/src/main/java/org/epics/util/array/UnsafeUnwrapper.java

**Comment by shroffk** [comment]
So the above class 

1. Takes care of type mapping.
2. It also runs checks so that you don't use a read only array for writing

**Comment by kasemir** [comment]
OK, that'll work.
