### ISSUE TITLE
VEnum handling of invalid index

### ISSUE THREAD

**Issue by kasemir** [epics-base/epicsCoreJava#45]
In theory, an enum value should come with enumeration labels for each state.
IVEnum checks if the numeric index is within the supported labels, 
https://github.com/epics-base/epicsCoreJava/blob/master/epics-vtype/vtype/src/main/java/org/epics/vtype/IVEnum.java#L24

In practice, there are enum PVs without proper labels.
Either because somebody forgot to configure them, or because a PV for a record's STAT field can only fetch 16 labels via Channel Access while the index can be higher.
In that case, getting an exception and not seeing any value is bad.
Better would be a VEnum that can wrap invalid indices, reporting the index as is, and when asked for a label, return a string like "Enum <47>" that might suggest to the user that this index has no valid label.

**Comment by kasemir** [comment]
Here's an example of an unfortunate BI record that's missing enum labels.
In the past, it would work, showing `<the index>` as a label:

![old](https://user-images.githubusercontent.com/1932421/50015089-b498fa80-ff93-11e8-8af5-1e4a70ce6e5d.png)

The plain VEnum will throw an exception.
Trying to work around as in https://github.com/shroffk/phoebus/commit/86604224c385fd7e97e2e59b9eb62eb939e40cc0 creates an alarm,
which seemed logical but changes the behavior of the alarm system
since that PV happens to be an alarm trigger:

![new](https://user-images.githubusercontent.com/1932421/50015103-bbc00880-ff93-11e8-8d19-1838c8484e30.png)

For now simply turning it into a VShort with the original alarm info,
https://github.com/shroffk/phoebus/pull/499/commits/669f876de088118953a42a1bea321cb4bd538199 : 

![again](https://user-images.githubusercontent.com/1932421/50015369-6801ef00-ff94-11e8-86c0-bc1a5b72e719.png)

**Comment by shroffk** [comment]
@kasemir can we close this issue

**Comment by kasemir** [comment]
We can close this issue because the EPICS code source code has been updated.
We still need to release it and/or update the phoebus dependencies to a 'snapshot' so we can benefit from the fox.
