### ISSUE TITLE
Epics Core support for openjdk8

### ISSUE THREAD

**Issue by shroffk** [epics-base/epicsCoreJava#84]
Should newer releases of epics core libraries continue to support openjdk 8.

Currently the CI builds are failing cause the released version of jca was built using openjdk11... due to which ByteBuffer.flip() returns a ByteBuffer... It used to return a Buffer in JDK8.

So we would have to update the code to have explicit changes in order to be able to run on jdk8. I am not sure this is worth the maintaince effort.

@kasemir @georgweiss

**Comment by georgweiss** [comment]
Well, what is the use case for jdk8 compatible artifacts? Are there development resources available that may help out in maintaining compatibility?

**Comment by shroffk** [comment]
> Well, what is the use case for jdk8 compatible artifacts?

I am not sure, since new development should be moving to jdk11 anyway. Exisiting applications which use older versions of java can use older versions of the libraries.

> Are there development resources available that may help out in maintaining compatibility?

Must be... but I have not looked into it.

**Comment by kasemir** [comment]
SLAC is one site using the new Java PVA client from Matlab, and ML can only load java 8 jars.
For CA, there are C-based implementations for Matlab, so doesn't use jca.
Not sure about imagj, though. It has jca bindings, and https://imagej.net/Downloads talks about "the ongoing transition from Java 6 to Java 8", so maybe it would have problems with a jca lib that requires java 11.

**Comment by shroffk** [comment]
Ok, it seems like there might be a few users still requiring openjdk8 support.

So I have created a separate branch and made a new release
`jca-2.4.4-j8` 
which is meant to work with openjdk8

I will bring up this issue at the next core meeting and in the release announcement and then we can decide how to proceed.

**Comment by kasemir** [comment]
Do you need to keep separate branches, or can the 'master' for now remain compatible with J8?

**Comment by shroffk** [comment]
The master is compatible for the time being.
However, the release 2.4.4 has been done and I can't replace it with new binaries

For the next release we can plan to merge the branches and build and release using openjdk8.... this has its own issues with the binaries not officially avaiable anymore.

**Comment by kasemir** [comment]
The most recent release is ahead of the master?

**Comment by shroffk** [comment]
This is kind of resolved.

The latest release 7.0.6 was done
1. on the master branch
2. using red hats's open jdk 8 and should thus be compliant with openjdk11 and openjdk8(at least the red hat version)
