### ISSUE TITLE
pvData structure arrays put usage

### ISSUE THREAD

**Issue by shroffk** [epics-base/epicsCoreJava#9]
The following code is trying to create a PVStructureArray.
In order to populate if I first create PVStructure[] with 2 NTScalars, the first a1 is complete and all the expected fields, a2 is a place holder and does not have all the expected fields (no alarm, no time)...

```

PVStructureArray p = PVDataFactory.getPVDataCreate().createPVStructureArray(NTScalar.createBuilder().value(ScalarType.pvDouble).addAlarm().addTimeStamp().createStructure());

NTScalar a1 = NTScalar.createBuilder().value(ScalarType.pvDouble).addAlarm().addTimeStamp().create();
NTScalar a2 = NTScalar.createBuilder().value(ScalarType.pvDouble).create();

Alarm alarm = new Alarm();
alarm.setSeverity(AlarmSeverity.getSeverity(1));
alarm.setStatus(AlarmStatus.getStatus(2));
		
PVAlarm af = PVAlarmFactory.create();
af.attach(a1.getAlarm());
af.set(alarm);
		
TimeStamp ts = TimeStampFactory.create();
ts.put(System.currentTimeMillis());
PVTimeStamp at = PVTimeStampFactory.create();
at.attach(a1.getTimeStamp());
at.set(ts);
		
a1.getValue(PVDouble.class).put(21);

a2.getValue(PVDouble.class).put(22);
		
PVStructure[] pvVals = new PVStructure[] { a1.getPVStructure(), a2.getPVStructure() };
```

In the final put I am copying only the first element 
```
p.put(0, 1, pvVals, 0);
```

however this fails with 
```
Exception in thread "main" java.lang.IllegalStateException: element is not a compatible structure
	at org.epics.pvdata.factory.BasePVStructureArray.put(BasePVStructureArray.java:83)
```

I am not sure why the put is checking the compatibility of structures not being copied in.

**Comment by ralphlange** [comment]
I'm really not sure if I can be of any help with this....

**Comment by mrkraimer** [comment]
In
> http://epics-pvdata.sourceforge.net/informative/developerGuide/developerGuide.html#overview:_pvdata
It states:
> structureArray
>     An array of structures. Each element must have the same
>     introspection interface. 

What you are trying to do is to create a unionArray
>
> union
>     A field that has a single sub field which can dynamically change
>     type. A variant union allows any valid type. A restricted union
>     allows for a set of valid types.
> unionArray
>     A array of unions. Each element must have the same introspection
>     interface.
>
>

Marty

**Comment by shroffk** [comment]
Hi, 

>  structureArray
     An array of structures. Each element must have the same
     introspection interface.

Yes, this is fine... a1, has the same introspection interface.
A unionArray would make sense if I was copying both a1 AND a2 .... but I am only asking the pvStructureArray to copy a single element, a1, which does satisfy the introspection requirement.

**Comment by mrkraimer** [comment]
```
 Each element must have the same
introspection interface.
```

means the same instance of the introspection interface.
You had:
```
NTScalar a1 = NTScalar.createBuilder().value(ScalarType.pvDouble).addAlarm().addTimeStamp().create();
NTScalar a2 = NTScalar.createBuilder().value(ScalarType.pvDouble).create();
```

Replaces these by

```
PVStructure a1 = PVDataFactory.getPVDataCreate().createPVStructure(p.getStructureArray().getStructure());
PVStructure a2 = PVDataFactory.getPVDataCreate().createPVStructure(p.getStructureArray().getStructure());
```

Does this help?

**Comment by shroffk** [comment]
Let me try to clarify my problem...
I am not sure why the put is checking the compatibility of structures not being copied in????

In the final put I am copying only the first element - the element which does 

p.put(0, 1, pvVals, 0);

However this fails with

Exception in thread "main" java.lang.IllegalStateException: element is not a compatible structure
	at org.epics.pvdata.factory.BasePVStructureArray.put(BasePVStructureArray.java:83)

**Comment by mrkraimer** [comment]
OK now I think I understand your concern. The code in question is:
```
public int put(int offset, int len, PVStructure[] from, int fromOffset) {
    	
    	// first check if all the PVStructure-s are of the right type
    	Structure elementField = structureArray.getStructure();
    	for (PVStructure pvs : from)
    		if (pvs != null && !pvs.getStructure().equals(elementField))
    			throw new IllegalStateException("element is not a compatible structure");
    	
    	return internalPut(offset, len, from, fromOffset);
    }
```

This is checking all elements of the array instead of just the elements that are used,
It seems that this could be changed to
```
 public int put(int offset, int len, PVStructure[] from, int fromOffset) {
        // first check if the PVStructure-s are of the right type
        Structure elementField = structureArray.getStructure();
        for(int i=fromOffset; i < from.length; ++i) {
            PVStructure pvs = from[i];
            if (pvs != null && !pvs.getStructure().equals(elementField))
                throw new IllegalStateException("element is not a compatible structure");
        }
        return internalPut(offset, len, from, fromOffset);
    }
```

**Comment by shroffk** [comment]
yes..this is exactly it :)
