### ISSUE TITLE
jca version

### ISSUE THREAD

**Issue by shroffk** [epics-base/epicsCoreJava#90]
It looks like the parent pom has a hardcoded version of the jca version.
This should be replaced with the use of the jca.version property

**Comment by ralphlange** [comment]
Where exactly does it look that way?

**Comment by shroffk** [comment]
in the parent pom.xml
Since the parent is released first without children ( -N) 
the original parent release in sonatype has the wrong version... I am tempted to delete the artifact and try to release just the parent but there are a lot of warning online about doing this :(

**Comment by ralphlange** [comment]
But looking at the parent pom (https://github.com/epics-base/epicsCoreJava/blob/master/pom.xml) I don't see where it would be set hardcoded.

**Comment by shroffk** [comment]
The issue is on the release/7.0 branch

**Comment by shroffk** [comment]
@georgweiss 

I feel we might want to consider merging the master and the release/7.0

That way we have fewer branches to manage and fewer fixes to cherry pick across.

**Comment by kasemir** [comment]
I don't understand the branching.
Ordinarily, 'master' is the latest usable code, and releases are a little older, frozen in time, except for getting some cherry-picked bug fixes.

But in this case 'master' is stuck in last summer, while releases charge ahead.

![Screen Shot 2020-05-12 at 9 43 20 AM](https://user-images.githubusercontent.com/1932421/81699259-141f6200-9435-11ea-97a7-c8d08a021102.png)

![Screen Shot 2020-05-12 at 9 43 30 AM](https://user-images.githubusercontent.com/1932421/81699267-17b2e900-9435-11ea-8819-83983dec2da3.png)

**Comment by shroffk** [comment]
@kasemir the release/7.0 was part of the general branch pattern which was used by all epics-base repos at the start.

The CPP repos then switched to master branch for releases. 

I agree with you that an up to date master is more in keeping with what one would expect from most project. 

Hence we could merge the release back into master.
Perform tag releases on master.
Create release branches with patches only when needed to maintain compatibility.

@ralphlange @georgweiss please  +1 if you agree with above.

**Comment by shroffk** [comment]
So...
I have merged the branches, the release branch is now merged into master
I fixed how the jca version in the released parent
I did a new release from the master branch - release 7.0.6

@georgweiss can you check if this resolves the build issues

**Comment by shroffk** [comment]
There is one last thing that persists.
When releasing the versions are explicitly added to the pom of each module being release. I will look into this before the next release.

I have seen the recent phoebus builds succeed without the SNAPSHOT error which was the origin of this ticket
I hope it is ok to close this ticket now.
